# Generated by Django 5.2.8 on 2025-12-14 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('complaint', 'Complaint'), ('incident', 'Incident / Accident'), ('praise', 'Praise'), ('defect', 'Vehicle Defect'), ('feedback', 'General Feedback'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('social', 'Social Media'), ('in_person', 'In Person'), ('flixbus', 'FlixBus System'), ('internal', 'Internal / Staff')], max_length=20)),
                ('service_line', models.CharField(choices=[('flixbus', 'FlixBus'), ('school', 'Home to School'), ('private', 'Private Hire'), ('other', 'Other')], max_length=20)),
                ('occurred_at', models.DateTimeField(help_text='When the issue occurred')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('driver_name', models.CharField(blank=True, help_text='Driver involved (if applicable)', max_length=255)),
                ('vehicle_reference', models.CharField(blank=True, help_text='Vehicle registration or identifier', max_length=50)),
                ('route_reference', models.CharField(blank=True, help_text='Route, contract, or service reference', max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
