# Generated by Django 5.2.8 on 2025-12-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='is_open',
        ),
        migrations.AddField(
            model_name='interaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_assigned_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='closure_notes',
            field=models.TextField(blank=True, help_text='Summary of action taken and outcome'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('review', 'Under Review'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_logged_interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
