# Generated by Django 5.2.8 on 2025-12-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0002_remove_interaction_is_open_interaction_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='closure_notes',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interaction',
            name='manager_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='route_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='vehicle_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
