# Generated by Django 5.2.8 on 2025-12-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0005_interactionassignmentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='Unique investigation reference number', max_length=50, unique=True)),
                ('reason', models.TextField(help_text='Reason for investigation')),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_response', 'Awaiting Staff Response'), ('no_further_action', 'No Further Action'), ('training', 'Training Required'), ('disciplinary', 'Escalated to Disciplinary'), ('closed', 'Closed')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investigations', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Investigation Created'), ('notice_sent', 'Investigation Notice Sent'), ('notice_viewed', 'Employee Viewed Notice'), ('response_submitted', 'Employee Response Submitted'), ('decision_made', 'Manager Decision Recorded'), ('closed', 'Investigation Closed'), ('escalated', 'Escalated to Disciplinary')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='qms.investigation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
