# Generated by Django 5.2.8 on 2025-12-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0006_investigation_investigationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='case_number',
            field=models.CharField(blank=True, help_text='Unique investigation reference number', max_length=50, unique=True),
        ),
    ]
