# Generated by Django 5.2.8 on 2025-12-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0007_alter_investigation_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Investigation Created'), ('notice_sent', 'Investigation Notice Sent'), ('notice_viewed', 'Employee Viewed Notice'), ('response_submitted', 'Employee Response Submitted'), ('evidence_submitted', 'Evidence Submitted'), ('decision_made', 'Manager Decision Recorded'), ('closed', 'Investigation Closed'), ('escalated', 'Escalated to Disciplinary')], max_length=30),
        ),
    ]
