# Generated by Django 5.2.8 on 2025-12-20 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0009_qmsauthority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qmsauthority',
            name='notes',
        ),
        migrations.AddField(
            model_name='qmsauthority',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsauthority',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsauthority',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_qms_authorities', to=settings.AUTH_USER_MODEL),
        ),
    ]
