# Generated by Django 5.2.8 on 2025-12-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0010_remove_qmsauthority_notes_qmsauthority_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('PRIMARY_AUTHORITY', 'Primary QMS Authority Register'), ('DEPOT_RESPONSIBILITY', 'Depot Responsibility Register'), ('STAFF_RESPONSIBILITY', 'Staff Responsibility Register')], max_length=50)),
                ('object_ref', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
