# Generated by Django 5.2.8 on 2025-12-29 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('route_created', 'Route created'), ('route_discontinued', 'Route discontinued'), ('journey_updated', 'Journey updated')], max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('old_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('new_delay_minutes', models.IntegerField(blank=True, null=True)),
                ('old_reason', models.TextField(blank=True, default='')),
                ('new_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_changes', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='home.opsjourney')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='home.opsroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
