# Generated by Django 5.2.8 on 2025-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_opstodoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsjourney',
            name='diversion_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opsjourney',
            name='status',
            field=models.CharField(choices=[('on_time', 'On time'), ('delayed', 'Delayed'), ('diversion', 'On diversion'), ('cancelled', 'Cancelled')], default='on_time', max_length=20),
        ),
    ]
