# Generated by Django 5.2.8 on 2025-12-30 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_opsjourney_diversion_details_alter_opsjourney_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opstodoitem',
            options={},
        ),
        migrations.AddField(
            model_name='opstodoitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_todos_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opstodoitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opstodoitem',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_todos_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opstodoitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_todos_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
