# Generated by Django 5.2.8 on 2025-12-30 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_opstodoitem_options_opstodoitem_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opstodoitem',
            options={'ordering': ['is_done', '-created_at'], 'verbose_name': 'Ops To-do', 'verbose_name_plural': 'Ops To-dos'},
        ),
        migrations.AlterField(
            model_name='opstodoitem',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_todos_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
