# Generated by Django 5.2.8 on 2025-11-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shop_open', models.BooleanField(default=True)),
                ('ordering_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Settings',
            },
        ),
    ]
