# Generated by Django 5.2.8 on 2025-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_allow_payroll_purchase_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('DISPATCHED', 'Dispatched / Sent'), ('COLLECTED', 'Collected')], default='PENDING', max_length=20),
        ),
    ]
