# Generated by Django 5.2.8 on 2025-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_managerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image link'),
        ),
    ]
